In [7]:

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Cargar las variables de entorno desde el archivo .env
load_dotenv()

# Obtener la ruta desde las variables de entorno
scripts_path = Path(os.getenv("SCRIPTS_PATH"))
sys.path.append(str(scripts_path))

from config import DB_HOST, DB_USER, DB_PASSWORD, DB_NAME  # Importar credenciales
from queries import QUERY_qx  # Importar la consulta SQL

In [8]:
import pandas as pd

# Convertir el resultado del query en un DataFrame
columns = [desc[0] for desc in cursor.description]  # Obtener los nombres de las columnas
df_result = pd.DataFrame(result, columns=columns)

# Mostrar el DataFramE
df_result

,BF5BBFI1221BI_B2129FIJF,BF5BBFI1221BI_F5997JB9F,BF5BBFI1221BI_Y7FY7YF1B,-- Clave\nCOUNT(BF5BBFI1221BI_Y7FY7YF1B)
0,Broncoscopia fibroóptica,D,3322,275
1,Otra broncoscopia,D,3323,162
2,Drenaje de cavidad pleural por toracoscopía,Q,3406,135
3,Otra septoplastia,Q,2188,126
4,Laringoscopia y otra traqueoscopia,D,3142,122
...,...,...,...,...
363,"Operaciones sobre el cuerpo carotídeo, seno ca...",Q,398X,1
364,Aspiración y lavado de seno maxilar,None,220,1
365,Hemicolectomía derecha por laparoscopía,Q,457C,1
366,Otra reparación de hernia,None,539,1
367,Otra esofagoscopía,D,4223,1

In [6]:
# Renombrar las columnas del DataFrame
df_result.rename(columns={
    'BF5BBFI1221BI_B2129FIJF': 'Descripción',
    'BF5BBFI1221BI_F5997JB9F': 'Tipo',
    'BF5BBFI1221BI_Y7FY7YF1B': 'Clave',
    '-- Clave\nCOUNT(BF5BBFI1221BI_Y7FY7YF1B)': 'Conteo por Clave'
}, inplace=True)

# Mostrar el DataFrame con los nuevos nombres de columnas
df_result

,Descripción,Tipo,Clave,Conteo por Clave
0,Broncoscopia fibroóptica,D,3322,275
1,Otra broncoscopia,D,3323,162
2,Drenaje de cavidad pleural por toracoscopía,Q,3406,135
3,Otra septoplastia,Q,2188,126
4,Laringoscopia y otra traqueoscopia,D,3142,122
...,...,...,...,...
363,Pericardiocentesis,None,370,1
364,Otras operaciones sobre hígado,None,509,1
365,Biopsia cerrada [endoscópica] de tráquea,D,3144,1
366,"Otra inmovilización, presión y cuidado de herida",T,9359,1
367,Otra endoscopía de intestino delgado,D,4513,1